org: thorgus

service: government

plugins:
  - serverless-domain-manager
  - serverless-python-requirements
  - serverless-wsgi

package:
  exclude:
    - node_modules/**
    - .idea/**
    - .requirements/**
    - venv/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: 'forms-table-${self:custom.stage}'
  wsgi:
    app: application.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  domains:
    prod: government.fernandojr.dev
    staging: staging.government.fernandojr.dev
    dev: dev.government.fernandojr.dev
  customDomain:
    basePath: ''
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: '${self:custom.stage}'
    createRoute53Record: true

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource:
        - { "Fn::GetAtt": ["FormsDynamoDBTable", "Arn" ] }
  environment:
    FORMS_TABLE: ${self:custom.tableName}
    STAGE: ${self:custom.stage}

functions:
  getForm:
    handler: wsgi_handler.handler
    events:
      - http: 'GET /forms/{proxy+}'
  createForm:
    handler: wsgi_handler.handler
    events:
      - http: 'POST /forms'
  listForm:
    handler: wsgi_handler.handler
    events:
      - http: 'GET /forms'
  updateForm:
    handler: wsgi_handler.handler
    events:
      - http: 'PUT /forms/{proxy+}'
  deleteForm:
    handler: wsgi_handler.handler
    events:
      - http: 'DELETE /forms/{proxy+}'

resources:
  Resources:
    FormsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
